"""Evaluation profiles package."""

from framework.profiles.travel import (
    TRAVEL_PROFILE,
    TRAVEL_ROUTE_OPTIMIZATION_PROFILE,
    TRAVEL_REMOTE_WORKER_TIMEZONES_PROFILE,
    TRAVEL_MID_TRIP_REPLANNING_PROFILE,
    TRAVEL_INFORMATION_GATHERING_UNCERTAINTY_PROFILE,
    PROFILE_REGISTRY,
)
