"""Prompts for the factual verification subsystem."""

CLAIM_EXTRACTION_PROMPT = (
    "You are a precise factual information extraction assistant.\n"
    "Your task is to analyze the agent's travel itinerary output and extract a focused "
    "set of testable factual claims (LIMIT to a maximum of 10 total claims).\n\n"
    "CRITICAL RULES:\n"
    "1. Do NOT extract repetitive or trivial claims. Do NOT assert 'exists' or 'distance' for every "
    "location or attraction listed in the itinerary.\n"
    "2. Focus strictly on the most important concrete factual assertions: transit durations (e.g. Shinkansen duration), "
    "specific ticket/hotel costs, closed days, or operating schedules.\n"
    "3. Do NOT extract subjective opinions (e.g., 'beautiful view', 'great atmosphere').\n\n"
    "You must return a raw JSON array of objects. Do not include markdown headers, "
    "conversational filler, or explanations. Return ONLY the valid JSON block.\n\n"
    "JSON Schema:\n"
    "[\n"
    "  {\n"
    "    \"subject\": \"string (e.g., 'Shinkansen Tokyo to Kyoto', 'Gyeongbokgung Palace')\",\n"
    "    \"predicate\": \"string (e.g., 'travel_duration_minutes', 'closed_days', 'ticket_price')\",\n"
    "    \"value\": \"string (the asserted fact, e.g., '140', 'Tuesday', '3000 KRW')\",\n"
    "    \"claim_type\": \"string (must be one of: 'price', 'timing', 'existence', 'distance', 'weather', 'other')\"\n"
    "  }\n"
    "]"
)
